# Generated by Django 4.1.7 on 2023-03-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peticions',
            options={'verbose_name': 'Petition', 'verbose_name_plural': 'Petitions'},
        ),
    ]
