# Generated by Django 4.1.7 on 2023-03-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0002_alter_peticions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticions',
            name='name_surname',
            field=models.TextField(default='My name', verbose_name='name_surname'),
        ),
    ]
