# Generated by Django 4.1.7 on 2023-03-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0003_peticions_name_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticions',
            name='name_surname',
            field=models.TextField(verbose_name='name_surname'),
        ),
    ]
