# Generated by Django 4.1.7 on 2023-03-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0004_alter_peticions_name_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticions',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
