# Generated by Django 4.1.7 on 2023-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0008_peticions_vote_count_alter_peticions_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
